import os

# SQLALCHEMY_TRACK_MODIFICATIONS = False
# DEBUG = True
SECRET_KEY = os.urandom(24)
HOSTNAME = '10.10.10.111'
PORT = 3306
DATABASE = 'NewMovie'
USERNAME = 'root'
PASSWORD = '1'
# DB_URI = 'mysql+pymysql://{}:{}@{}:{}/{}?charset=utf8'.format(USERNAME, PASSWORD,HOSTNAME, PORT, DATABASE )
# SQLALCHEMY_DATABASE_URI = DB_URI
# SQLALCHEMY_TRACK_MODIFICATIONS = False
